# fly.toml app configuration file generated for rewrite-ai on 2025-01-21T00:55:43Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rewrite-ai'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
